"""Write index.html listing every <LANG>/*.html page, grouped by language folder.

Usage: python3 build_index.py && python3 inline.py index.html
(safe to rerun; CI runs both before every Pages deploy)
"""
import base64, glob, html, os, re
ROOT = os.path.dirname(os.path.abspath(__file__))
def meta(path):
    src = open(path, encoding='utf-8').read()
    title = re.search(r'<title>(.*?)</title>', src, re.S)
    lang = re.search(r'<html[^>]*\blang="([^"]+)"', src)
    return html.unescape(title[1].strip()) if title else os.path.basename(path), lang[1] if lang else ''

groups = {}
for path in sorted(glob.glob(os.path.join(ROOT, '*', '*.html'))):
    groups.setdefault(os.path.basename(os.path.dirname(path)), []).append((os.path.relpath(path, ROOT), *meta(path)))

ACCENTS = ['#d4ff00', '#ff4d1a', '#00d9ff', '#ff3df2', '#ffd400']
e = html.escape
sections, ticker = [], []
for i, (folder, pages) in enumerate(groups.items(), 1):
    lang = pages[0][2] or folder.lower()
    items = ''.join(
        f'<li><a href="{e(rel)}" hreflang="{e(l)}"><span class="no">{i:02}.{j}</span>'
        f'<span class="t" lang="{e(l)}">{e(t)}</span><span class="p">{e(rel)}</span><span class="go" aria-hidden="true">&#8599;</span></a></li>'
        for j, (rel, t, l) in enumerate(pages, 1))
    sections.append(
        f'<section style="--a:{ACCENTS[(i - 1) % len(ACCENTS)]}"><div class="in">'
        f'<h2><span class="idx">{i:02}</span><span class="code">{e(folder)}</span>'
        f'<span class="name" data-lang="{e(lang)}" lang="{e(lang)}">{e(folder)}</span>'
        f'<span class="cnt">&times;{len(pages):02}</span></h2>'
        f'<p class="serial" aria-hidden="true">LNG-{e(folder)}/{i:04} &nbsp;//&nbsp; {e(lang)}</p><ul>{items}</ul></div></section>')
    ticker += [f'<b>{e(folder)}</b>'] + [e(t) for _, t, _ in pages]
# base64 keeps the icon offline and out of inline.py's leftover-URL check (the xmlns would trip it)
FAVICON = base64.b64encode(b'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">'
    b'<path fill="#d4ff00" d="M6 0h26v26l-6 6H0V6z"/><path fill="#0b0b0c" d="M8 8h16v5h-5.5v12h-5V13H8z"/></svg>').decode()
total = sum(len(p) for p in groups.values())

PAGE = '''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Tabula Sordida</title>
<link rel="icon" href="data:image/svg+xml;base64,@FAVICON@">
<!-- generated by build_index.py; edit the script, not this file -->
<link href="https://fonts.googleapis.com/css2?family=Tektur:wght@500;800&amp;family=JetBrains+Mono:wght@400;700&amp;display=swap" rel="stylesheet">
<style>
:root{--k:#0b0b0c;--k2:#141416;--w:#ecebe4;--dim:#8d8c86;--acid:#d4ff00;--hot:#ff4d1a;--cy:#00d9ff;--mg:#ff3df2;
--mono:"JetBrains Mono",ui-monospace,monospace;--disp:"Tektur","Arial Narrow",sans-serif;--cut:18px}
*{box-sizing:border-box}
html{background:var(--k)}
body{margin:0;min-height:100vh;color:var(--w);font:15px/1.45 var(--disp);overflow-x:hidden;
background:linear-gradient(#ffffff08 1px,transparent 1px) 0 0/32px 32px,linear-gradient(90deg,#ffffff08 1px,transparent 1px) 0 0/32px 32px,var(--k)}
::selection{background:var(--acid);color:var(--k)}
.top,.serial,.no,.p,.cnt,.stats,.tag,footer{font-family:var(--mono)}
.top{display:flex;flex-wrap:wrap;gap:8px 20px;align-items:center;padding:10px 16px;border-bottom:2px solid var(--w);font-size:11px;letter-spacing:.12em;text-transform:uppercase}
.top .dot{width:8px;height:8px;background:var(--acid);display:inline-block;margin-right:6px;animation:blink 1.2s steps(2) infinite}
.top .bar{flex:1;min-width:80px;height:14px;background:repeating-linear-gradient(90deg,var(--w) 0 2px,transparent 2px 4px,var(--w) 4px 5px,transparent 5px 9px,var(--w) 9px 12px,transparent 12px 14px)}
@keyframes blink{50%{opacity:0}}
main{max-width:1120px;margin:0 auto;padding:0 16px 48px}
.hero{position:relative;padding:56px 0 32px}
.hero::before{content:"";position:absolute;right:0;top:40px;width:min(38%,380px);height:120px;
background:repeating-linear-gradient(-45deg,var(--hot) 0 10px,transparent 10px 20px);clip-path:polygon(40px 0,100% 0,100% 100%,0 100%,0 40px)}
.hero::after{content:"+";position:absolute;left:-4px;top:28px;font:400 20px var(--mono);color:var(--acid)}
h1{position:relative;margin:0;font:800 clamp(3rem,13vw,9.5rem)/.82 var(--disp);letter-spacing:-.04em;text-transform:uppercase}
h1 span{display:block}
h1 .o{color:transparent;-webkit-text-stroke:2px var(--w);padding-left:.55em}
h1 .o::before{content:"";display:inline-block;width:.5em;height:.12em;margin:0 .06em .2em -.62em;background:var(--acid);transform:skewX(-45deg)}
.tag{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:28px 0 0;font-size:13px;color:var(--dim);text-transform:uppercase;letter-spacing:.1em}
.tag::before{content:"";width:48px;height:2px;background:var(--acid)}
.stats{display:flex;margin:32px 0 40px;font-size:12px;text-transform:uppercase;letter-spacing:.14em}
.stats div{padding:10px 18px;background:var(--w);color:var(--k);clip-path:polygon(0 0,calc(100% - 12px) 0,100% 12px,100% 100%,0 100%)}
.stats div+div{background:var(--acid);margin-left:6px}
.stats b{display:block;font:800 32px/1 var(--disp);letter-spacing:-.02em}
.ticker{overflow:hidden;border-block:2px solid var(--w);background:var(--acid);color:var(--k);white-space:nowrap;margin:0 -16px 40px;
font:800 14px/1 var(--disp);text-transform:uppercase;letter-spacing:.06em}
.ticker div{display:inline-block;padding:10px 0;animation:tick 40s linear infinite}
.ticker b{background:var(--k);color:var(--acid);padding:2px 6px}
.ticker i{font-style:normal;color:var(--hot)}
@keyframes tick{to{transform:translateX(-50%)}}
.grid{display:grid;gap:28px;grid-template-columns:repeat(auto-fill,minmax(min(100%,460px),1fr))}
section{--poly:polygon(var(--cut) 0,100% 0,100% calc(100% - var(--cut)),calc(100% - var(--cut)) 100%,0 100%,0 var(--cut));
background:var(--a);padding:2px;clip-path:var(--poly);transition:transform .15s}
section:hover{transform:translate(-3px,-3px)}
.in{position:relative;height:100%;background:var(--k2);clip-path:var(--poly);padding-bottom:28px}
.in::after{content:"";position:absolute;right:26px;bottom:9px;width:46px;height:8px;background:repeating-linear-gradient(-45deg,var(--a) 0 3px,transparent 3px 6px)}
h2{display:flex;align-items:stretch;margin:0;background:var(--a);color:var(--k);font:800 20px/1 var(--disp);text-transform:uppercase}
h2>span{display:flex;align-items:center;padding:12px 14px}
h2>.idx{background:var(--k);color:var(--a);padding:12px 22px 12px calc(var(--cut) + 6px);clip-path:polygon(0 0,100% 0,calc(100% - 12px) 100%,0 100%)}
.code{font-size:28px;letter-spacing:-.02em}
.name{flex:1;font-weight:500;font-size:16px;letter-spacing:.04em;border-left:2px solid var(--k)}
.cnt{margin-left:auto;font-size:12px;font-weight:700}
.serial{margin:10px 16px 12px;font-size:10px;letter-spacing:.18em;color:var(--dim);text-transform:uppercase}
ul{list-style:none;margin:0;padding:0 14px;display:grid;gap:6px}
li a{display:grid;grid-template-columns:auto 1fr auto;gap:2px 14px;align-items:center;padding:12px 14px;color:inherit;text-decoration:none;
border:1px solid #ffffff22;border-left:4px solid var(--a);background:#ffffff05;transition:background .12s,color .12s,transform .12s}
.no{grid-row:span 2;font-size:11px;color:var(--a)}
.t{font-weight:800;font-size:17px;line-height:1.2;text-transform:uppercase;letter-spacing:.01em}
.p{grid-column:2;font-size:11px;color:var(--dim);overflow-wrap:anywhere}
.go{grid-row:1/span 2;grid-column:3;font:800 22px var(--disp);color:var(--a)}
li a:hover,li a:focus-visible{background:var(--a);color:var(--k);transform:translateX(4px)}
li a:hover :is(.no,.p,.go),li a:focus-visible :is(.no,.p,.go){color:var(--k)}
a:focus-visible{outline:2px solid var(--w);outline-offset:3px}
footer{display:flex;flex-wrap:wrap;justify-content:space-between;gap:12px;margin-top:56px;padding-top:14px;border-top:2px solid var(--w);
font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--dim)}
footer a{color:var(--acid);text-decoration:none}footer a:hover{background:var(--acid);color:var(--k)}
.top a{color:var(--k);background:var(--acid);padding:2px 6px;text-decoration:none}.top a:hover{background:var(--w)}
footer .stripe{flex-basis:100%;height:12px;background:repeating-linear-gradient(-45deg,var(--acid) 0 8px,var(--k) 8px 16px,var(--hot) 16px 24px,var(--k) 24px 32px,var(--cy) 32px 40px,var(--k) 40px 48px,var(--mg) 48px 56px,var(--k) 56px 64px)}
@media (max-width:560px){.hero::before{width:45%;height:70px;top:20px}.name{display:none}.stats b{font-size:26px}}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style>
</head>
<body>
<div class="top"><span><span class="dot"></span>SYS.IDX // ONLINE</span><span>TS-01 / PAGE DIRECTORY</span><span class="bar" aria-hidden="true"></span><a href="https://github.com/Kseen715/tabula-sordida">GitHub &#8599;</a></div>
<main>
<div class="hero">
<h1><span>Tabula</span><span class="o">Sordida</span></h1>
<p class="tag">Offline page archive <span>&#9656;</span> sorted by language</p>
</div>
<div class="stats"><div><b>@TOTAL@</b>pages</div><div><b>@LANGS@</b>languages</div></div>
<div class="ticker" aria-hidden="true"><div>@TICK@ <i>///</i> @TICK@ <i>///</i> </div></div>
<div class="grid">
@SECTIONS@
</div>
<footer><span class="stripe" aria-hidden="true"></span><span>Tabula Sordida // index</span><a href="https://github.com/Kseen715/tabula-sordida">github.com/Kseen715/tabula-sordida</a><span>&#9632; &#9632; &#9632; EOF</span></footer>
</main>
<script>
// native language names ("de" -> "Deutsch"); folder code stays as fallback
for (const el of document.querySelectorAll('[data-lang]')) {
  try { el.textContent = new Intl.DisplayNames([el.dataset.lang], {type: 'language'}).of(el.dataset.lang); } catch {}
}
</script>
</body>
</html>
'''
page = (PAGE.replace('@TOTAL@', f'{total:02}').replace('@LANGS@', f'{len(groups):02}')
        .replace('@TICK@', ' <i>///</i> '.join(ticker)).replace('@SECTIONS@', '\n'.join(sections)).replace('@FAVICON@', FAVICON))
open(os.path.join(ROOT, 'index.html'), 'w', encoding='utf-8').write(page)
print(f'index.html: {total} pages in {len(groups)} languages')
